AeroRust/nmea

.github/workflows/ci.yml
codecov.yml

Calculate coverage

---

Cargo.toml
src/lib.rs
src/parse.rs
src/sentences/mod.rs
src/sentences/txt.rs

Hi, I added a u-blox TXT message support.
Any feedback is welcome, especially on public interface: I used easiest way to expose a message, `Nmea::last_txt`, which returns latest TXT message, and user could pull a message with following code
```rust
match nmea.parse(&line) {
Ok(nmea::SententType::TXT) => {
let txt = nmea.last_txt();
},
}
```
It exposes `TxtData` directly to public interface, and I'm not sure if it's okay.

u-blox TXT support

---

src/lib.rs
src/parse.rs
src/sentences/txt.rs
src/sentences/utils.rs

As a first step of the no_std compatability we can just use core instead of std when possible since lots of std is actually just core re-exports.

use core when possible instead of std

---

Cargo.toml
src/parse.rs

Hey! 👋 
I'm trying to use this crate and have the errors propagated up. It looks like `Error` is not implemented for `NmeaError`, so here is a PR to fix that.
We implement Display unconditionally for `NmeaError`, and `std::error::Error`when working in a `std` environment.
To distinguish between `no_std` and `std` we add an optional but enabled by default `std` feature. As far as I can tell, rust doesn't yet have a proper way to do this...

Implement Display+Error for NmeaError

---

src/sentences/rmc.rs
src/sentences/utils.rs

We are incorrectly parsing the two digit year in RMC messages. (i.e. 94 is parsed as year 0094 instead of 1994.)
Since RMC messages only include two digits, the year is ambiguous. This PR changes the parsing to parse anything over 83 as 1900's and anything over 0 as 2000's.
The reason for choosing 83 as the cutoff year is that NMEA0183 was released in 1983.

Fix two digit year parsing in RMC messages

---

src/lib.rs
src/sentences/gll.rs
src/sentences/mod.rs

Due to a bug in parsing we were never actually filling the PosSysIndicator in GLL Messages. We also never exposed this type outside the crate, this PR fixes that.

Fix parsing and expose PosSysIndicator in GLL Messages

---

src/error.rs
src/parse.rs
src/parser.rs
src/sentences/mod.rs
src/sentences/rmz.rs

`$PGRMZ` is used by a lot of gliding computers like the https://gliding.lxnav.com/products/lx9000/ to transmit the current barometric altitude.
This PR implements basic support for it. It is currently implemented to output the raw altitude in feet without any conversions.

Implement `PGRMZ` support

---

src/sentences/bod.rs

This PR adds 5 tests for parsing BOD, using the two examples from gpsd's [BOD - Bearing - Waypoint to Waypoint](https://gpsd.gitlab.io/gpsd/NMEA.html#_bod_bearing_waypoint_to_waypoint). The checksums were not correct so they were recalculated.
The tests cover sentences with active route, and without (described as GOTO mode in the reference page):
- active route format
- both waypoints
- missing destination waypoint field
- missing origin waypoint field
- GOTO mode
- missing bearing field
The current implementation only worked for the active route format (i.e both waypoints are present), so I fixed the implementation to pass all tests.

Add tests to BOD and fix parsing

---

Cargo.toml
benches/gsv_parser.rs
benches/nom_parsing.rs
src/sentences/bod.rs

This PR introduces [`criterion`](https://github.com/bheisler/criterion.rs) as a dev-dependency to run benchmarks, instead of the nightly `bencher`.
The `gsv_parser` benchmark module now uses Criterion, and a new `nom_parsing` module has been added to compare parsing strategies for comma-separated values.
If we have `let sentence = "a,b";` the strategies are:
- the "discard comma" strategy already used in the crate:
```rust
let (i, a) = char('a')(text)?;
let (i, _) = char(',')(i)?; // the parsed comma is discarded with _
let (i, b) = char('b')(i)?;
```
- the `preceded` combinator:
```rust
let (i, a) = char('a')(text)?;
let (i, b) = preceded(char(','), char('b'))(i)?;
```
Run `cargo bench` to run the benchmarks.
I initially thought that there would be significant performance improvement by …

Use criterion for benchmarks and update bod parsing

---

README.md
src/parse.rs
src/parser.rs
src/sentences/mda.rs
src/sentences/mod.rs
src/sentences/mwv.rs
tests/all_supported_messages.rs

Adds a pair of parsers for WIMDA and WIMWV. No GPS Fix related messaging parsing for this set as they are both weather station based messages.

Adds MWV and MDA parsers

---

README.md
src/parse.rs
src/parser.rs
src/sentences/mod.rs
src/sentences/mtw.rs

Add MTW sentence parser

---

README.md
src/lib.rs
src/parse.rs
src/parser.rs
src/sentences/mod.rs
src/sentences/zda.rs
tests/all_supported_messages.rs
tests/functional_tests.rs

#54 Implements parser for ZDA sentence.
Does `NMEA::parse_for_fix`  need to support `ZDA` ? I've not implemented it yet. 🤔

Add ZDA sentence parser

---

README.md
src/parse.rs
src/parser.rs
src/sentences/mod.rs
src/sentences/utils.rs
src/sentences/zfo.rs
src/sentences/ztg.rs
tests/all_supported_messages.rs

Based on:
https://gpsd.gitlab.io/gpsd/NMEA.html#_zfo_utc_time_from_origin_waypoint
https://gpsd.gitlab.io/gpsd/NMEA.html#_ztg_utc_time_to_destination_waypoint

Added parsing ZFO and ZTG messages

---

src/parse.rs
src/sentences/aam.rs
src/sentences/bod.rs
src/sentences/bwc.rs
src/sentences/bww.rs
src/sentences/txt.rs
src/sentences/utils.rs
src/sentences/zfo.rs
src/sentences/ztg.rs

During experiments with c bindings for nmea library, found that multiple MAX_LEN consts are used around. All of the same value (64). This causes cbindgen to generate single const with ambiguous meaning.
When I look closer, found that I've used manual conversion waypoint ids to ArrayString, while proper array_string method is already done. This PR fixes this as well, and because array_string is used just for parameters, I've updated error with more proper one (ParameterLength).

Unified handling text parameters

---

Cargo.toml
src/sentences/gga.rs

Implement no_std serialization for NaiveTime

---

src/parse.rs
src/sentences/alm.rs
src/sentences/dbk.rs
src/sentences/mtw.rs
src/sentences/zda.rs
tests/file_log_parser.rs

Currently main is failing when running `cargo clippy --no-deps -- -D warnings`. This PR fixes those errors.

fix clippy warnings

---

Cargo.toml
README.md
src/lib.rs
src/parse.rs
src/parser.rs
src/sentences/mod.rs
src/sentences/ttm.rs
tests/all_supported_messages.rs

https://github.com/AeroRust/nmea/issues/54 Add TTM sentence parse support
TTM is a stand-alone feature, but part of a new feature called "radar", when other radar messages as TLL or TLB is introduced.

Add TTM sentence parse support

---

src/sentences/utils.rs

connect: https://github.com/AeroRust/nmea/issues/25

Increase test coverage for src/sentences/utils.rs

---

Cargo.toml
README.md
src/lib.rs
src/parse.rs
src/parser.rs
src/sentences/dpt.rs
src/sentences/mod.rs
src/sentences/utils.rs
tests/all_supported_messages.rs

connect: https://github.com/AeroRust/nmea/issues/54

Prepare implementation for DPT (Depth of Water) messages

---

src/sentences/gsv.rs

I noticed that `parse("$GQGSV,...")` returns `UnknownGnssType("GQ")` instead of `GSV(GsvData { gnss_type: Qzss, ... })`. I fixed this so that it can parse `GQ` as `GnssType::Qzss`.

Parse talker ID `GQ` as QZSS

---

src/parser.rs
src/sentences/gll.rs

Based on my experiment with u-blox MAX-M10S, UTC time in the GLL message is not always available (specifically after power cycling). This PR changes the type of `GllData.fix_time` to `Option<NaiveTime>` like other messages such as `RmcData`.

Make `GllData.fix_time` optional

---

src/error.rs

This fixes compilation errors like below:
```
error[E0277]: the trait bound `nom::internal::Err<nom::error::Error<&str>>: Format` is not satisfied
--> nyan.rs:245:21
|
245 |                     defmt::warn!("{:a}: {}", line, err);
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Format` is not implemented for `nom::internal::Err<nom::error::Error<&str>>`
|
= help: the following other types implement trait `Format`:
&T
&mut T
()
(T0, T1)
(T0, T1, T2)
(T0, T1, T2, T3)
(T0, T1, T2, T3, T4)
(T0, T1, T2, T3, T4, T5)
and 234 others
= note: required for `nmea::Error<'_>` to implement `Format`
note: required by a bound in `defmt::export::fmt`
```
The position of adding the `#[defmt()]` attribute seems to be wrong according to the …

Fix compilation error when printing `Error` with defmt
